# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9773e4949858c99bc5c3685133caf279281cd06414de474449edd756a822ab8fa4293d2ef3704867be42df62c0c3df8dd0e642f71260e49e754e29a9cddf748e

test:
  secret_key_base: bbdceba5f22b46a793919a27e0990a8443813bfdb916d63a86e50afd68e2f39f336de1b553d3de92a7a2b95e2a4f1ac88f0904596dd4d2a49d838ea01145be59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
